drop table mapping;

drop table midi_control;
drop table midi_device;

drop table sacn_channel;
drop table sacn;

create table midi_device (
	id integer primary key autoincrement,
	name text not null,
	mode text not null check (mode in ('off','in','out'))
);

create table midi_control (
	id_midi_device integer not null,
	id integer primary key autoincrement,
	name text not null check (name in ('fader','knob','button')),
	num integer not null,
	ch integer not null check (ch >=0 and ch <= 15),
	signal_type text not null check ( signal_type in ('cc','note')),
	signal_num int not null check ( signal_num >=0 and  signal_num <=127),
	foreign key(id_midi_device) references midi_device(id)
		on update cascade
		on delete cascade
);

create table sacn (
	id integer primary key autoincrement,
	ip_address text not null,
	universe integer not null,
	mode text not null check (mode in ('off','in','out'))
);

create table sacn_channel (
	id_sacn integer not null,
	id integer primary key autoincrement,
	ch_num integer not null,
	foreign key(id_sacn) references sacn(id)
		on update cascade
		on delete cascade
);

create table mapping (
	id_midi_control integer not null,
	id_sacn_channel integer not null,
	foreign key(id_midi_control) references midi_control(id),
	foreign key(id_sacn_channel) references sacn_channel(id)
		on update cascade
		on delete cascade
);
insert into midi_device ( name, mode ) values ('Launch Control', 'in');
insert into midi_device ( name, mode ) values ('Launch Control', 'out');
insert into midi_device ( name, mode ) values ('Launch Control', 'off');
insert into midi_device ( name, mode ) values ('APC mini', 'in');
insert into midi_device ( name, mode ) values ('APC mini', 'out');
insert into midi_device ( name, mode ) values ('APC mini', 'off');
insert into midi_device ( name, mode ) values ('Launch Pad MKII', 'in');
insert into midi_device ( name, mode ) values ('Launch Pad MKII', 'out');
insert into midi_device ( name, mode ) values ('Launch Pad MKII', 'off');

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',1,0,'cc',21);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',2,0,'cc',22);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',3,0,'cc',23);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',4,0,'cc',24);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',5,0,'cc',25);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',6,0,'cc',26);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',7,0,'cc',27);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',8,0,'cc',28);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',9,0,'cc',41);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',10,0,'cc',42);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',11,0,'cc',43);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',12,0,'cc',44);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',13,0,'cc',45);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',14,0,'cc',46);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',15,0,'cc',47);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'knob',16,0,'cc',48);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',1,0,'note',9);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',2,0,'note',10);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',3,0,'note',11);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',4,0,'note',12);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',5,0,'note',25);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',6,0,'note',26);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',7,0,'note',27);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',8,0,'note',28);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',9,0,'cc',114);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',10,0,'cc',115);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',11,0,'cc',116);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (1,'button',12,0,'cc',117);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',1,0,'cc',21);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',2,0,'cc',22);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',3,0,'cc',23);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',4,0,'cc',24);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',5,0,'cc',25);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',6,0,'cc',26);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',7,0,'cc',27);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',8,0,'cc',28);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',9,0,'cc',41);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',10,0,'cc',42);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',11,0,'cc',43);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',12,0,'cc',44);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',13,0,'cc',45);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',14,0,'cc',46);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',15,0,'cc',47);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'knob',16,0,'cc',48);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',1,0,'note',9);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',2,0,'note',10);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',3,0,'note',11);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',4,0,'note',12);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',5,0,'note',25);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',6,0,'note',26);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',7,0,'note',27);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',8,0,'note',28);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',9,0,'cc',114);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',10,0,'cc',115);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',11,0,'cc',116);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (2,'button',12,0,'cc',117);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',1,0,'cc',21);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',2,0,'cc',22);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',3,0,'cc',23);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',4,0,'cc',24);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',5,0,'cc',25);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',6,0,'cc',26);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',7,0,'cc',27);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',8,0,'cc',28);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',9,0,'cc',41);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',10,0,'cc',42);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',11,0,'cc',43);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',12,0,'cc',44);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',13,0,'cc',45);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',14,0,'cc',46);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',15,0,'cc',47);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'knob',16,0,'cc',48);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',1,0,'note',9);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',2,0,'note',10);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',3,0,'note',11);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',4,0,'note',12);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',5,0,'note',25);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',6,0,'note',26);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',7,0,'note',27);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',8,0,'note',28);

insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',9,0,'cc',114);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',10,0,'cc',115);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',11,0,'cc',116);
insert into midi_control ( id_midi_device, name, num, ch, signal_type, signal_num ) values (3,'button',12,0,'cc',117);

insert into sacn (ip_address, universe, mode) values ('2.1.1.2', 221,'out');
insert into sacn (ip_address, universe, mode) values ('2.1.1.2', 222,'out');
insert into sacn_channel (id_sacn, ch_num) values (1,1);
insert into sacn_channel (id_sacn, ch_num) values (1,2);
insert into sacn_channel (id_sacn, ch_num) values (1,3);
insert into sacn_channel (id_sacn, ch_num) values (1,4);
insert into sacn_channel (id_sacn, ch_num) values (1,5);
insert into sacn_channel (id_sacn, ch_num) values (1,6);
insert into sacn_channel (id_sacn, ch_num) values (1,7);
insert into sacn_channel (id_sacn, ch_num) values (1,8);
insert into sacn_channel (id_sacn, ch_num) values (1,9);
insert into sacn_channel (id_sacn, ch_num) values (1,10);
insert into sacn_channel (id_sacn, ch_num) values (1,11);
insert into sacn_channel (id_sacn, ch_num) values (1,12);
insert into sacn_channel (id_sacn, ch_num) values (1,13);
insert into sacn_channel (id_sacn, ch_num) values (1,14);
insert into sacn_channel (id_sacn, ch_num) values (1,15);
insert into sacn_channel (id_sacn, ch_num) values (1,16);
insert into sacn_channel (id_sacn, ch_num) values (1,17);
insert into sacn_channel (id_sacn, ch_num) values (1,18);
insert into sacn_channel (id_sacn, ch_num) values (1,19);
insert into sacn_channel (id_sacn, ch_num) values (1,20);
insert into sacn_channel (id_sacn, ch_num) values (1,21);
insert into sacn_channel (id_sacn, ch_num) values (1,22);
insert into sacn_channel (id_sacn, ch_num) values (1,23);
insert into sacn_channel (id_sacn, ch_num) values (1,24);
insert into sacn_channel (id_sacn, ch_num) values (1,25);
insert into sacn_channel (id_sacn, ch_num) values (1,26);
insert into sacn_channel (id_sacn, ch_num) values (1,27);
insert into sacn_channel (id_sacn, ch_num) values (1,28);
insert into sacn_channel (id_sacn, ch_num) values (1,29);
insert into sacn_channel (id_sacn, ch_num) values (1,30);
insert into sacn_channel (id_sacn, ch_num) values (1,31);
insert into sacn_channel (id_sacn, ch_num) values (1,32);
insert into sacn_channel (id_sacn, ch_num) values (1,33);
insert into sacn_channel (id_sacn, ch_num) values (1,34);
insert into sacn_channel (id_sacn, ch_num) values (1,35);
insert into sacn_channel (id_sacn, ch_num) values (1,36);
insert into sacn_channel (id_sacn, ch_num) values (1,37);
insert into sacn_channel (id_sacn, ch_num) values (1,38);
insert into sacn_channel (id_sacn, ch_num) values (1,39);
insert into sacn_channel (id_sacn, ch_num) values (1,40);
insert into sacn_channel (id_sacn, ch_num) values (1,41);
insert into sacn_channel (id_sacn, ch_num) values (1,42);
insert into sacn_channel (id_sacn, ch_num) values (1,43);
insert into sacn_channel (id_sacn, ch_num) values (1,44);
insert into sacn_channel (id_sacn, ch_num) values (1,45);
insert into sacn_channel (id_sacn, ch_num) values (1,46);
insert into sacn_channel (id_sacn, ch_num) values (1,47);
insert into sacn_channel (id_sacn, ch_num) values (1,48);
insert into sacn_channel (id_sacn, ch_num) values (1,49);
insert into sacn_channel (id_sacn, ch_num) values (1,50);
insert into sacn_channel (id_sacn, ch_num) values (1,51);
insert into sacn_channel (id_sacn, ch_num) values (1,52);
insert into sacn_channel (id_sacn, ch_num) values (1,53);
insert into sacn_channel (id_sacn, ch_num) values (1,54);
insert into sacn_channel (id_sacn, ch_num) values (1,55);
insert into sacn_channel (id_sacn, ch_num) values (1,56);
insert into sacn_channel (id_sacn, ch_num) values (1,57);
insert into sacn_channel (id_sacn, ch_num) values (1,58);
insert into sacn_channel (id_sacn, ch_num) values (1,59);
insert into sacn_channel (id_sacn, ch_num) values (1,60);
insert into sacn_channel (id_sacn, ch_num) values (1,61);
insert into sacn_channel (id_sacn, ch_num) values (1,62);
insert into sacn_channel (id_sacn, ch_num) values (1,63);
insert into sacn_channel (id_sacn, ch_num) values (1,64);
insert into sacn_channel (id_sacn, ch_num) values (1,65);
insert into sacn_channel (id_sacn, ch_num) values (1,66);
insert into sacn_channel (id_sacn, ch_num) values (1,67);
insert into sacn_channel (id_sacn, ch_num) values (1,68);
insert into sacn_channel (id_sacn, ch_num) values (1,69);
insert into sacn_channel (id_sacn, ch_num) values (1,70);
insert into sacn_channel (id_sacn, ch_num) values (1,71);
insert into sacn_channel (id_sacn, ch_num) values (1,72);
insert into sacn_channel (id_sacn, ch_num) values (1,73);
insert into sacn_channel (id_sacn, ch_num) values (1,74);
insert into sacn_channel (id_sacn, ch_num) values (1,75);
insert into sacn_channel (id_sacn, ch_num) values (1,76);
insert into sacn_channel (id_sacn, ch_num) values (1,77);
insert into sacn_channel (id_sacn, ch_num) values (1,78);
insert into sacn_channel (id_sacn, ch_num) values (1,79);
insert into sacn_channel (id_sacn, ch_num) values (1,80);
insert into sacn_channel (id_sacn, ch_num) values (1,81);
insert into sacn_channel (id_sacn, ch_num) values (1,82);
insert into sacn_channel (id_sacn, ch_num) values (1,83);
insert into sacn_channel (id_sacn, ch_num) values (1,84);
insert into sacn_channel (id_sacn, ch_num) values (1,85);
insert into sacn_channel (id_sacn, ch_num) values (1,86);
insert into sacn_channel (id_sacn, ch_num) values (1,87);
insert into sacn_channel (id_sacn, ch_num) values (1,88);
insert into sacn_channel (id_sacn, ch_num) values (1,89);
insert into sacn_channel (id_sacn, ch_num) values (1,90);
insert into sacn_channel (id_sacn, ch_num) values (1,91);
insert into sacn_channel (id_sacn, ch_num) values (1,92);
insert into sacn_channel (id_sacn, ch_num) values (1,93);
insert into sacn_channel (id_sacn, ch_num) values (1,94);
insert into sacn_channel (id_sacn, ch_num) values (1,95);
insert into sacn_channel (id_sacn, ch_num) values (1,96);
insert into sacn_channel (id_sacn, ch_num) values (1,97);
insert into sacn_channel (id_sacn, ch_num) values (1,98);
insert into sacn_channel (id_sacn, ch_num) values (1,99);
insert into sacn_channel (id_sacn, ch_num) values (1,100);
insert into sacn_channel (id_sacn, ch_num) values (1,101);
insert into sacn_channel (id_sacn, ch_num) values (1,102);
insert into sacn_channel (id_sacn, ch_num) values (1,103);
insert into sacn_channel (id_sacn, ch_num) values (1,104);
insert into sacn_channel (id_sacn, ch_num) values (1,105);
insert into sacn_channel (id_sacn, ch_num) values (1,106);
insert into sacn_channel (id_sacn, ch_num) values (1,107);
insert into sacn_channel (id_sacn, ch_num) values (1,108);
insert into sacn_channel (id_sacn, ch_num) values (1,109);
insert into sacn_channel (id_sacn, ch_num) values (1,110);
insert into sacn_channel (id_sacn, ch_num) values (1,111);
insert into sacn_channel (id_sacn, ch_num) values (1,112);
insert into sacn_channel (id_sacn, ch_num) values (1,113);
insert into sacn_channel (id_sacn, ch_num) values (1,114);
insert into sacn_channel (id_sacn, ch_num) values (1,115);
insert into sacn_channel (id_sacn, ch_num) values (1,116);
insert into sacn_channel (id_sacn, ch_num) values (1,117);
insert into sacn_channel (id_sacn, ch_num) values (1,118);
insert into sacn_channel (id_sacn, ch_num) values (1,119);
insert into sacn_channel (id_sacn, ch_num) values (1,120);
insert into sacn_channel (id_sacn, ch_num) values (1,121);
insert into sacn_channel (id_sacn, ch_num) values (1,122);
insert into sacn_channel (id_sacn, ch_num) values (1,123);
insert into sacn_channel (id_sacn, ch_num) values (1,124);
insert into sacn_channel (id_sacn, ch_num) values (1,125);
insert into sacn_channel (id_sacn, ch_num) values (1,126);
insert into sacn_channel (id_sacn, ch_num) values (1,127);
insert into sacn_channel (id_sacn, ch_num) values (1,128);
insert into sacn_channel (id_sacn, ch_num) values (1,129);
insert into sacn_channel (id_sacn, ch_num) values (1,130);
insert into sacn_channel (id_sacn, ch_num) values (1,131);
insert into sacn_channel (id_sacn, ch_num) values (1,132);
insert into sacn_channel (id_sacn, ch_num) values (1,133);
insert into sacn_channel (id_sacn, ch_num) values (1,134);
insert into sacn_channel (id_sacn, ch_num) values (1,135);
insert into sacn_channel (id_sacn, ch_num) values (1,136);
insert into sacn_channel (id_sacn, ch_num) values (1,137);
insert into sacn_channel (id_sacn, ch_num) values (1,138);
insert into sacn_channel (id_sacn, ch_num) values (1,139);
insert into sacn_channel (id_sacn, ch_num) values (1,140);
insert into sacn_channel (id_sacn, ch_num) values (1,141);
insert into sacn_channel (id_sacn, ch_num) values (1,142);
insert into sacn_channel (id_sacn, ch_num) values (1,143);
insert into sacn_channel (id_sacn, ch_num) values (1,144);
insert into sacn_channel (id_sacn, ch_num) values (1,145);
insert into sacn_channel (id_sacn, ch_num) values (1,146);
insert into sacn_channel (id_sacn, ch_num) values (1,147);
insert into sacn_channel (id_sacn, ch_num) values (1,148);
insert into sacn_channel (id_sacn, ch_num) values (1,149);
insert into sacn_channel (id_sacn, ch_num) values (1,150);
insert into sacn_channel (id_sacn, ch_num) values (1,151);
insert into sacn_channel (id_sacn, ch_num) values (1,152);
insert into sacn_channel (id_sacn, ch_num) values (1,153);
insert into sacn_channel (id_sacn, ch_num) values (1,154);
insert into sacn_channel (id_sacn, ch_num) values (1,155);
insert into sacn_channel (id_sacn, ch_num) values (1,156);
insert into sacn_channel (id_sacn, ch_num) values (1,157);
insert into sacn_channel (id_sacn, ch_num) values (1,158);
insert into sacn_channel (id_sacn, ch_num) values (1,159);
insert into sacn_channel (id_sacn, ch_num) values (1,160);
insert into sacn_channel (id_sacn, ch_num) values (1,161);
insert into sacn_channel (id_sacn, ch_num) values (1,162);
insert into sacn_channel (id_sacn, ch_num) values (1,163);
insert into sacn_channel (id_sacn, ch_num) values (1,164);
insert into sacn_channel (id_sacn, ch_num) values (1,165);
insert into sacn_channel (id_sacn, ch_num) values (1,166);
insert into sacn_channel (id_sacn, ch_num) values (1,167);
insert into sacn_channel (id_sacn, ch_num) values (1,168);
insert into sacn_channel (id_sacn, ch_num) values (1,169);
insert into sacn_channel (id_sacn, ch_num) values (1,170);
insert into sacn_channel (id_sacn, ch_num) values (1,171);
insert into sacn_channel (id_sacn, ch_num) values (1,172);
insert into sacn_channel (id_sacn, ch_num) values (1,173);
insert into sacn_channel (id_sacn, ch_num) values (1,174);
insert into sacn_channel (id_sacn, ch_num) values (1,175);
insert into sacn_channel (id_sacn, ch_num) values (1,176);
insert into sacn_channel (id_sacn, ch_num) values (1,177);
insert into sacn_channel (id_sacn, ch_num) values (1,178);
insert into sacn_channel (id_sacn, ch_num) values (1,179);
insert into sacn_channel (id_sacn, ch_num) values (1,180);
insert into sacn_channel (id_sacn, ch_num) values (1,181);
insert into sacn_channel (id_sacn, ch_num) values (1,182);
insert into sacn_channel (id_sacn, ch_num) values (1,183);
insert into sacn_channel (id_sacn, ch_num) values (1,184);
insert into sacn_channel (id_sacn, ch_num) values (1,185);
insert into sacn_channel (id_sacn, ch_num) values (1,186);
insert into sacn_channel (id_sacn, ch_num) values (1,187);
insert into sacn_channel (id_sacn, ch_num) values (1,188);
insert into sacn_channel (id_sacn, ch_num) values (1,189);
insert into sacn_channel (id_sacn, ch_num) values (1,190);
insert into sacn_channel (id_sacn, ch_num) values (1,191);
insert into sacn_channel (id_sacn, ch_num) values (1,192);
insert into sacn_channel (id_sacn, ch_num) values (1,193);
insert into sacn_channel (id_sacn, ch_num) values (1,194);
insert into sacn_channel (id_sacn, ch_num) values (1,195);
insert into sacn_channel (id_sacn, ch_num) values (1,196);
insert into sacn_channel (id_sacn, ch_num) values (1,197);
insert into sacn_channel (id_sacn, ch_num) values (1,198);
insert into sacn_channel (id_sacn, ch_num) values (1,199);
insert into sacn_channel (id_sacn, ch_num) values (1,200);
insert into sacn_channel (id_sacn, ch_num) values (1,201);
insert into sacn_channel (id_sacn, ch_num) values (1,202);
insert into sacn_channel (id_sacn, ch_num) values (1,203);
insert into sacn_channel (id_sacn, ch_num) values (1,204);
insert into sacn_channel (id_sacn, ch_num) values (1,205);
insert into sacn_channel (id_sacn, ch_num) values (1,206);
insert into sacn_channel (id_sacn, ch_num) values (1,207);
insert into sacn_channel (id_sacn, ch_num) values (1,208);
insert into sacn_channel (id_sacn, ch_num) values (1,209);
insert into sacn_channel (id_sacn, ch_num) values (1,210);
insert into sacn_channel (id_sacn, ch_num) values (1,211);
insert into sacn_channel (id_sacn, ch_num) values (1,212);
insert into sacn_channel (id_sacn, ch_num) values (1,213);
insert into sacn_channel (id_sacn, ch_num) values (1,214);
insert into sacn_channel (id_sacn, ch_num) values (1,215);
insert into sacn_channel (id_sacn, ch_num) values (1,216);
insert into sacn_channel (id_sacn, ch_num) values (1,217);
insert into sacn_channel (id_sacn, ch_num) values (1,218);
insert into sacn_channel (id_sacn, ch_num) values (1,219);
insert into sacn_channel (id_sacn, ch_num) values (1,220);
insert into sacn_channel (id_sacn, ch_num) values (1,221);
insert into sacn_channel (id_sacn, ch_num) values (1,222);
insert into sacn_channel (id_sacn, ch_num) values (1,223);
insert into sacn_channel (id_sacn, ch_num) values (1,224);
insert into sacn_channel (id_sacn, ch_num) values (1,225);
insert into sacn_channel (id_sacn, ch_num) values (1,226);
insert into sacn_channel (id_sacn, ch_num) values (1,227);
insert into sacn_channel (id_sacn, ch_num) values (1,228);
insert into sacn_channel (id_sacn, ch_num) values (1,229);
insert into sacn_channel (id_sacn, ch_num) values (1,230);
insert into sacn_channel (id_sacn, ch_num) values (1,231);
insert into sacn_channel (id_sacn, ch_num) values (1,232);
insert into sacn_channel (id_sacn, ch_num) values (1,233);
insert into sacn_channel (id_sacn, ch_num) values (1,234);
insert into sacn_channel (id_sacn, ch_num) values (1,235);
insert into sacn_channel (id_sacn, ch_num) values (1,236);
insert into sacn_channel (id_sacn, ch_num) values (1,237);
insert into sacn_channel (id_sacn, ch_num) values (1,238);
insert into sacn_channel (id_sacn, ch_num) values (1,239);
insert into sacn_channel (id_sacn, ch_num) values (1,240);
insert into sacn_channel (id_sacn, ch_num) values (1,241);
insert into sacn_channel (id_sacn, ch_num) values (1,242);
insert into sacn_channel (id_sacn, ch_num) values (1,243);
insert into sacn_channel (id_sacn, ch_num) values (1,244);
insert into sacn_channel (id_sacn, ch_num) values (1,245);
insert into sacn_channel (id_sacn, ch_num) values (1,246);
insert into sacn_channel (id_sacn, ch_num) values (1,247);
insert into sacn_channel (id_sacn, ch_num) values (1,248);
insert into sacn_channel (id_sacn, ch_num) values (1,249);
insert into sacn_channel (id_sacn, ch_num) values (1,250);
insert into sacn_channel (id_sacn, ch_num) values (1,251);
insert into sacn_channel (id_sacn, ch_num) values (1,252);
insert into sacn_channel (id_sacn, ch_num) values (1,253);
insert into sacn_channel (id_sacn, ch_num) values (1,254);
insert into sacn_channel (id_sacn, ch_num) values (1,255);
insert into sacn_channel (id_sacn, ch_num) values (1,256);
insert into sacn_channel (id_sacn, ch_num) values (1,257);
insert into sacn_channel (id_sacn, ch_num) values (1,258);
insert into sacn_channel (id_sacn, ch_num) values (1,259);
insert into sacn_channel (id_sacn, ch_num) values (1,260);
insert into sacn_channel (id_sacn, ch_num) values (1,261);
insert into sacn_channel (id_sacn, ch_num) values (1,262);
insert into sacn_channel (id_sacn, ch_num) values (1,263);
insert into sacn_channel (id_sacn, ch_num) values (1,264);
insert into sacn_channel (id_sacn, ch_num) values (1,265);
insert into sacn_channel (id_sacn, ch_num) values (1,266);
insert into sacn_channel (id_sacn, ch_num) values (1,267);
insert into sacn_channel (id_sacn, ch_num) values (1,268);
insert into sacn_channel (id_sacn, ch_num) values (1,269);
insert into sacn_channel (id_sacn, ch_num) values (1,270);
insert into sacn_channel (id_sacn, ch_num) values (1,271);
insert into sacn_channel (id_sacn, ch_num) values (1,272);
insert into sacn_channel (id_sacn, ch_num) values (1,273);
insert into sacn_channel (id_sacn, ch_num) values (1,274);
insert into sacn_channel (id_sacn, ch_num) values (1,275);
insert into sacn_channel (id_sacn, ch_num) values (1,276);
insert into sacn_channel (id_sacn, ch_num) values (1,277);
insert into sacn_channel (id_sacn, ch_num) values (1,278);
insert into sacn_channel (id_sacn, ch_num) values (1,279);
insert into sacn_channel (id_sacn, ch_num) values (1,280);
insert into sacn_channel (id_sacn, ch_num) values (1,281);
insert into sacn_channel (id_sacn, ch_num) values (1,282);
insert into sacn_channel (id_sacn, ch_num) values (1,283);
insert into sacn_channel (id_sacn, ch_num) values (1,284);
insert into sacn_channel (id_sacn, ch_num) values (1,285);
insert into sacn_channel (id_sacn, ch_num) values (1,286);
insert into sacn_channel (id_sacn, ch_num) values (1,287);
insert into sacn_channel (id_sacn, ch_num) values (1,288);
insert into sacn_channel (id_sacn, ch_num) values (1,289);
insert into sacn_channel (id_sacn, ch_num) values (1,290);
insert into sacn_channel (id_sacn, ch_num) values (1,291);
insert into sacn_channel (id_sacn, ch_num) values (1,292);
insert into sacn_channel (id_sacn, ch_num) values (1,293);
insert into sacn_channel (id_sacn, ch_num) values (1,294);
insert into sacn_channel (id_sacn, ch_num) values (1,295);
insert into sacn_channel (id_sacn, ch_num) values (1,296);
insert into sacn_channel (id_sacn, ch_num) values (1,297);
insert into sacn_channel (id_sacn, ch_num) values (1,298);
insert into sacn_channel (id_sacn, ch_num) values (1,299);
insert into sacn_channel (id_sacn, ch_num) values (1,300);
insert into sacn_channel (id_sacn, ch_num) values (1,301);
insert into sacn_channel (id_sacn, ch_num) values (1,302);
insert into sacn_channel (id_sacn, ch_num) values (1,303);
insert into sacn_channel (id_sacn, ch_num) values (1,304);
insert into sacn_channel (id_sacn, ch_num) values (1,305);
insert into sacn_channel (id_sacn, ch_num) values (1,306);
insert into sacn_channel (id_sacn, ch_num) values (1,307);
insert into sacn_channel (id_sacn, ch_num) values (1,308);
insert into sacn_channel (id_sacn, ch_num) values (1,309);
insert into sacn_channel (id_sacn, ch_num) values (1,310);
insert into sacn_channel (id_sacn, ch_num) values (1,311);
insert into sacn_channel (id_sacn, ch_num) values (1,312);
insert into sacn_channel (id_sacn, ch_num) values (1,313);
insert into sacn_channel (id_sacn, ch_num) values (1,314);
insert into sacn_channel (id_sacn, ch_num) values (1,315);
insert into sacn_channel (id_sacn, ch_num) values (1,316);
insert into sacn_channel (id_sacn, ch_num) values (1,317);
insert into sacn_channel (id_sacn, ch_num) values (1,318);
insert into sacn_channel (id_sacn, ch_num) values (1,319);
insert into sacn_channel (id_sacn, ch_num) values (1,320);
insert into sacn_channel (id_sacn, ch_num) values (1,321);
insert into sacn_channel (id_sacn, ch_num) values (1,322);
insert into sacn_channel (id_sacn, ch_num) values (1,323);
insert into sacn_channel (id_sacn, ch_num) values (1,324);
insert into sacn_channel (id_sacn, ch_num) values (1,325);
insert into sacn_channel (id_sacn, ch_num) values (1,326);
insert into sacn_channel (id_sacn, ch_num) values (1,327);
insert into sacn_channel (id_sacn, ch_num) values (1,328);
insert into sacn_channel (id_sacn, ch_num) values (1,329);
insert into sacn_channel (id_sacn, ch_num) values (1,330);
insert into sacn_channel (id_sacn, ch_num) values (1,331);
insert into sacn_channel (id_sacn, ch_num) values (1,332);
insert into sacn_channel (id_sacn, ch_num) values (1,333);
insert into sacn_channel (id_sacn, ch_num) values (1,334);
insert into sacn_channel (id_sacn, ch_num) values (1,335);
insert into sacn_channel (id_sacn, ch_num) values (1,336);
insert into sacn_channel (id_sacn, ch_num) values (1,337);
insert into sacn_channel (id_sacn, ch_num) values (1,338);
insert into sacn_channel (id_sacn, ch_num) values (1,339);
insert into sacn_channel (id_sacn, ch_num) values (1,340);
insert into sacn_channel (id_sacn, ch_num) values (1,341);
insert into sacn_channel (id_sacn, ch_num) values (1,342);
insert into sacn_channel (id_sacn, ch_num) values (1,343);
insert into sacn_channel (id_sacn, ch_num) values (1,344);
insert into sacn_channel (id_sacn, ch_num) values (1,345);
insert into sacn_channel (id_sacn, ch_num) values (1,346);
insert into sacn_channel (id_sacn, ch_num) values (1,347);
insert into sacn_channel (id_sacn, ch_num) values (1,348);
insert into sacn_channel (id_sacn, ch_num) values (1,349);
insert into sacn_channel (id_sacn, ch_num) values (1,350);
insert into sacn_channel (id_sacn, ch_num) values (1,351);
insert into sacn_channel (id_sacn, ch_num) values (1,352);
insert into sacn_channel (id_sacn, ch_num) values (1,353);
insert into sacn_channel (id_sacn, ch_num) values (1,354);
insert into sacn_channel (id_sacn, ch_num) values (1,355);
insert into sacn_channel (id_sacn, ch_num) values (1,356);
insert into sacn_channel (id_sacn, ch_num) values (1,357);
insert into sacn_channel (id_sacn, ch_num) values (1,358);
insert into sacn_channel (id_sacn, ch_num) values (1,359);
insert into sacn_channel (id_sacn, ch_num) values (1,360);
insert into sacn_channel (id_sacn, ch_num) values (1,361);
insert into sacn_channel (id_sacn, ch_num) values (1,362);
insert into sacn_channel (id_sacn, ch_num) values (1,363);
insert into sacn_channel (id_sacn, ch_num) values (1,364);
insert into sacn_channel (id_sacn, ch_num) values (1,365);
insert into sacn_channel (id_sacn, ch_num) values (1,366);
insert into sacn_channel (id_sacn, ch_num) values (1,367);
insert into sacn_channel (id_sacn, ch_num) values (1,368);
insert into sacn_channel (id_sacn, ch_num) values (1,369);
insert into sacn_channel (id_sacn, ch_num) values (1,370);
insert into sacn_channel (id_sacn, ch_num) values (1,371);
insert into sacn_channel (id_sacn, ch_num) values (1,372);
insert into sacn_channel (id_sacn, ch_num) values (1,373);
insert into sacn_channel (id_sacn, ch_num) values (1,374);
insert into sacn_channel (id_sacn, ch_num) values (1,375);
insert into sacn_channel (id_sacn, ch_num) values (1,376);
insert into sacn_channel (id_sacn, ch_num) values (1,377);
insert into sacn_channel (id_sacn, ch_num) values (1,378);
insert into sacn_channel (id_sacn, ch_num) values (1,379);
insert into sacn_channel (id_sacn, ch_num) values (1,380);
insert into sacn_channel (id_sacn, ch_num) values (1,381);
insert into sacn_channel (id_sacn, ch_num) values (1,382);
insert into sacn_channel (id_sacn, ch_num) values (1,383);
insert into sacn_channel (id_sacn, ch_num) values (1,384);
insert into sacn_channel (id_sacn, ch_num) values (1,385);
insert into sacn_channel (id_sacn, ch_num) values (1,386);
insert into sacn_channel (id_sacn, ch_num) values (1,387);
insert into sacn_channel (id_sacn, ch_num) values (1,388);
insert into sacn_channel (id_sacn, ch_num) values (1,389);
insert into sacn_channel (id_sacn, ch_num) values (1,390);
insert into sacn_channel (id_sacn, ch_num) values (1,391);
insert into sacn_channel (id_sacn, ch_num) values (1,392);
insert into sacn_channel (id_sacn, ch_num) values (1,393);
insert into sacn_channel (id_sacn, ch_num) values (1,394);
insert into sacn_channel (id_sacn, ch_num) values (1,395);
insert into sacn_channel (id_sacn, ch_num) values (1,396);
insert into sacn_channel (id_sacn, ch_num) values (1,397);
insert into sacn_channel (id_sacn, ch_num) values (1,398);
insert into sacn_channel (id_sacn, ch_num) values (1,399);
insert into sacn_channel (id_sacn, ch_num) values (1,400);
insert into sacn_channel (id_sacn, ch_num) values (1,401);
insert into sacn_channel (id_sacn, ch_num) values (1,402);
insert into sacn_channel (id_sacn, ch_num) values (1,403);
insert into sacn_channel (id_sacn, ch_num) values (1,404);
insert into sacn_channel (id_sacn, ch_num) values (1,405);
insert into sacn_channel (id_sacn, ch_num) values (1,406);
insert into sacn_channel (id_sacn, ch_num) values (1,407);
insert into sacn_channel (id_sacn, ch_num) values (1,408);
insert into sacn_channel (id_sacn, ch_num) values (1,409);
insert into sacn_channel (id_sacn, ch_num) values (1,410);
insert into sacn_channel (id_sacn, ch_num) values (1,411);
insert into sacn_channel (id_sacn, ch_num) values (1,412);
insert into sacn_channel (id_sacn, ch_num) values (1,413);
insert into sacn_channel (id_sacn, ch_num) values (1,414);
insert into sacn_channel (id_sacn, ch_num) values (1,415);
insert into sacn_channel (id_sacn, ch_num) values (1,416);
insert into sacn_channel (id_sacn, ch_num) values (1,417);
insert into sacn_channel (id_sacn, ch_num) values (1,418);
insert into sacn_channel (id_sacn, ch_num) values (1,419);
insert into sacn_channel (id_sacn, ch_num) values (1,420);
insert into sacn_channel (id_sacn, ch_num) values (1,421);
insert into sacn_channel (id_sacn, ch_num) values (1,422);
insert into sacn_channel (id_sacn, ch_num) values (1,423);
insert into sacn_channel (id_sacn, ch_num) values (1,424);
insert into sacn_channel (id_sacn, ch_num) values (1,425);
insert into sacn_channel (id_sacn, ch_num) values (1,426);
insert into sacn_channel (id_sacn, ch_num) values (1,427);
insert into sacn_channel (id_sacn, ch_num) values (1,428);
insert into sacn_channel (id_sacn, ch_num) values (1,429);
insert into sacn_channel (id_sacn, ch_num) values (1,430);
insert into sacn_channel (id_sacn, ch_num) values (1,431);
insert into sacn_channel (id_sacn, ch_num) values (1,432);
insert into sacn_channel (id_sacn, ch_num) values (1,433);
insert into sacn_channel (id_sacn, ch_num) values (1,434);
insert into sacn_channel (id_sacn, ch_num) values (1,435);
insert into sacn_channel (id_sacn, ch_num) values (1,436);
insert into sacn_channel (id_sacn, ch_num) values (1,437);
insert into sacn_channel (id_sacn, ch_num) values (1,438);
insert into sacn_channel (id_sacn, ch_num) values (1,439);
insert into sacn_channel (id_sacn, ch_num) values (1,440);
insert into sacn_channel (id_sacn, ch_num) values (1,441);
insert into sacn_channel (id_sacn, ch_num) values (1,442);
insert into sacn_channel (id_sacn, ch_num) values (1,443);
insert into sacn_channel (id_sacn, ch_num) values (1,444);
insert into sacn_channel (id_sacn, ch_num) values (1,445);
insert into sacn_channel (id_sacn, ch_num) values (1,446);
insert into sacn_channel (id_sacn, ch_num) values (1,447);
insert into sacn_channel (id_sacn, ch_num) values (1,448);
insert into sacn_channel (id_sacn, ch_num) values (1,449);
insert into sacn_channel (id_sacn, ch_num) values (1,450);
insert into sacn_channel (id_sacn, ch_num) values (1,451);
insert into sacn_channel (id_sacn, ch_num) values (1,452);
insert into sacn_channel (id_sacn, ch_num) values (1,453);
insert into sacn_channel (id_sacn, ch_num) values (1,454);
insert into sacn_channel (id_sacn, ch_num) values (1,455);
insert into sacn_channel (id_sacn, ch_num) values (1,456);
insert into sacn_channel (id_sacn, ch_num) values (1,457);
insert into sacn_channel (id_sacn, ch_num) values (1,458);
insert into sacn_channel (id_sacn, ch_num) values (1,459);
insert into sacn_channel (id_sacn, ch_num) values (1,460);
insert into sacn_channel (id_sacn, ch_num) values (1,461);
insert into sacn_channel (id_sacn, ch_num) values (1,462);
insert into sacn_channel (id_sacn, ch_num) values (1,463);
insert into sacn_channel (id_sacn, ch_num) values (1,464);
insert into sacn_channel (id_sacn, ch_num) values (1,465);
insert into sacn_channel (id_sacn, ch_num) values (1,466);
insert into sacn_channel (id_sacn, ch_num) values (1,467);
insert into sacn_channel (id_sacn, ch_num) values (1,468);
insert into sacn_channel (id_sacn, ch_num) values (1,469);
insert into sacn_channel (id_sacn, ch_num) values (1,470);
insert into sacn_channel (id_sacn, ch_num) values (1,471);
insert into sacn_channel (id_sacn, ch_num) values (1,472);
insert into sacn_channel (id_sacn, ch_num) values (1,473);
insert into sacn_channel (id_sacn, ch_num) values (1,474);
insert into sacn_channel (id_sacn, ch_num) values (1,475);
insert into sacn_channel (id_sacn, ch_num) values (1,476);
insert into sacn_channel (id_sacn, ch_num) values (1,477);
insert into sacn_channel (id_sacn, ch_num) values (1,478);
insert into sacn_channel (id_sacn, ch_num) values (1,479);
insert into sacn_channel (id_sacn, ch_num) values (1,480);
insert into sacn_channel (id_sacn, ch_num) values (1,481);
insert into sacn_channel (id_sacn, ch_num) values (1,482);
insert into sacn_channel (id_sacn, ch_num) values (1,483);
insert into sacn_channel (id_sacn, ch_num) values (1,484);
insert into sacn_channel (id_sacn, ch_num) values (1,485);
insert into sacn_channel (id_sacn, ch_num) values (1,486);
insert into sacn_channel (id_sacn, ch_num) values (1,487);
insert into sacn_channel (id_sacn, ch_num) values (1,488);
insert into sacn_channel (id_sacn, ch_num) values (1,489);
insert into sacn_channel (id_sacn, ch_num) values (1,490);
insert into sacn_channel (id_sacn, ch_num) values (1,491);
insert into sacn_channel (id_sacn, ch_num) values (1,492);
insert into sacn_channel (id_sacn, ch_num) values (1,493);
insert into sacn_channel (id_sacn, ch_num) values (1,494);
insert into sacn_channel (id_sacn, ch_num) values (1,495);
insert into sacn_channel (id_sacn, ch_num) values (1,496);
insert into sacn_channel (id_sacn, ch_num) values (1,497);
insert into sacn_channel (id_sacn, ch_num) values (1,498);
insert into sacn_channel (id_sacn, ch_num) values (1,499);
insert into sacn_channel (id_sacn, ch_num) values (1,500);
insert into sacn_channel (id_sacn, ch_num) values (1,501);
insert into sacn_channel (id_sacn, ch_num) values (1,502);
insert into sacn_channel (id_sacn, ch_num) values (1,503);
insert into sacn_channel (id_sacn, ch_num) values (1,504);
insert into sacn_channel (id_sacn, ch_num) values (1,505);
insert into sacn_channel (id_sacn, ch_num) values (1,506);
insert into sacn_channel (id_sacn, ch_num) values (1,507);
insert into sacn_channel (id_sacn, ch_num) values (1,508);
insert into sacn_channel (id_sacn, ch_num) values (1,509);
insert into sacn_channel (id_sacn, ch_num) values (1,510);
insert into sacn_channel (id_sacn, ch_num) values (1,511);
insert into sacn_channel (id_sacn, ch_num) values (1,512);

insert into sacn_channel (id_sacn, ch_num) values (2,1);
insert into sacn_channel (id_sacn, ch_num) values (2,2);
insert into sacn_channel (id_sacn, ch_num) values (2,3);
insert into sacn_channel (id_sacn, ch_num) values (2,4);
insert into sacn_channel (id_sacn, ch_num) values (2,5);
insert into sacn_channel (id_sacn, ch_num) values (2,6);
insert into sacn_channel (id_sacn, ch_num) values (2,7);
insert into sacn_channel (id_sacn, ch_num) values (2,8);
insert into sacn_channel (id_sacn, ch_num) values (2,9);
insert into sacn_channel (id_sacn, ch_num) values (2,10);
insert into sacn_channel (id_sacn, ch_num) values (2,11);
insert into sacn_channel (id_sacn, ch_num) values (2,12);
insert into sacn_channel (id_sacn, ch_num) values (2,13);
insert into sacn_channel (id_sacn, ch_num) values (2,14);
insert into sacn_channel (id_sacn, ch_num) values (2,15);
insert into sacn_channel (id_sacn, ch_num) values (2,16);
insert into sacn_channel (id_sacn, ch_num) values (2,17);
insert into sacn_channel (id_sacn, ch_num) values (2,18);
insert into sacn_channel (id_sacn, ch_num) values (2,19);
insert into sacn_channel (id_sacn, ch_num) values (2,20);
insert into sacn_channel (id_sacn, ch_num) values (2,21);
insert into sacn_channel (id_sacn, ch_num) values (2,22);
insert into sacn_channel (id_sacn, ch_num) values (2,23);
insert into sacn_channel (id_sacn, ch_num) values (2,24);
insert into sacn_channel (id_sacn, ch_num) values (2,25);
insert into sacn_channel (id_sacn, ch_num) values (2,26);
insert into sacn_channel (id_sacn, ch_num) values (2,27);
insert into sacn_channel (id_sacn, ch_num) values (2,28);
insert into sacn_channel (id_sacn, ch_num) values (2,29);
insert into sacn_channel (id_sacn, ch_num) values (2,30);
insert into sacn_channel (id_sacn, ch_num) values (2,31);
insert into sacn_channel (id_sacn, ch_num) values (2,32);
insert into sacn_channel (id_sacn, ch_num) values (2,33);
insert into sacn_channel (id_sacn, ch_num) values (2,34);
insert into sacn_channel (id_sacn, ch_num) values (2,35);
insert into sacn_channel (id_sacn, ch_num) values (2,36);
insert into sacn_channel (id_sacn, ch_num) values (2,37);
insert into sacn_channel (id_sacn, ch_num) values (2,38);
insert into sacn_channel (id_sacn, ch_num) values (2,39);
insert into sacn_channel (id_sacn, ch_num) values (2,40);
insert into sacn_channel (id_sacn, ch_num) values (2,41);
insert into sacn_channel (id_sacn, ch_num) values (2,42);
insert into sacn_channel (id_sacn, ch_num) values (2,43);
insert into sacn_channel (id_sacn, ch_num) values (2,44);
insert into sacn_channel (id_sacn, ch_num) values (2,45);
insert into sacn_channel (id_sacn, ch_num) values (2,46);
insert into sacn_channel (id_sacn, ch_num) values (2,47);
insert into sacn_channel (id_sacn, ch_num) values (2,48);
insert into sacn_channel (id_sacn, ch_num) values (2,49);
insert into sacn_channel (id_sacn, ch_num) values (2,50);
insert into sacn_channel (id_sacn, ch_num) values (2,51);
insert into sacn_channel (id_sacn, ch_num) values (2,52);
insert into sacn_channel (id_sacn, ch_num) values (2,53);
insert into sacn_channel (id_sacn, ch_num) values (2,54);
insert into sacn_channel (id_sacn, ch_num) values (2,55);
insert into sacn_channel (id_sacn, ch_num) values (2,56);
insert into sacn_channel (id_sacn, ch_num) values (2,57);
insert into sacn_channel (id_sacn, ch_num) values (2,58);
insert into sacn_channel (id_sacn, ch_num) values (2,59);
insert into sacn_channel (id_sacn, ch_num) values (2,60);
insert into sacn_channel (id_sacn, ch_num) values (2,61);
insert into sacn_channel (id_sacn, ch_num) values (2,62);
insert into sacn_channel (id_sacn, ch_num) values (2,63);
insert into sacn_channel (id_sacn, ch_num) values (2,64);
insert into sacn_channel (id_sacn, ch_num) values (2,65);
insert into sacn_channel (id_sacn, ch_num) values (2,66);
insert into sacn_channel (id_sacn, ch_num) values (2,67);
insert into sacn_channel (id_sacn, ch_num) values (2,68);
insert into sacn_channel (id_sacn, ch_num) values (2,69);
insert into sacn_channel (id_sacn, ch_num) values (2,70);
insert into sacn_channel (id_sacn, ch_num) values (2,71);
insert into sacn_channel (id_sacn, ch_num) values (2,72);
insert into sacn_channel (id_sacn, ch_num) values (2,73);
insert into sacn_channel (id_sacn, ch_num) values (2,74);
insert into sacn_channel (id_sacn, ch_num) values (2,75);
insert into sacn_channel (id_sacn, ch_num) values (2,76);
insert into sacn_channel (id_sacn, ch_num) values (2,77);
insert into sacn_channel (id_sacn, ch_num) values (2,78);
insert into sacn_channel (id_sacn, ch_num) values (2,79);
insert into sacn_channel (id_sacn, ch_num) values (2,80);
insert into sacn_channel (id_sacn, ch_num) values (2,81);
insert into sacn_channel (id_sacn, ch_num) values (2,82);
insert into sacn_channel (id_sacn, ch_num) values (2,83);
insert into sacn_channel (id_sacn, ch_num) values (2,84);
insert into sacn_channel (id_sacn, ch_num) values (2,85);
insert into sacn_channel (id_sacn, ch_num) values (2,86);
insert into sacn_channel (id_sacn, ch_num) values (2,87);
insert into sacn_channel (id_sacn, ch_num) values (2,88);
insert into sacn_channel (id_sacn, ch_num) values (2,89);
insert into sacn_channel (id_sacn, ch_num) values (2,90);
insert into sacn_channel (id_sacn, ch_num) values (2,91);
insert into sacn_channel (id_sacn, ch_num) values (2,92);
insert into sacn_channel (id_sacn, ch_num) values (2,93);
insert into sacn_channel (id_sacn, ch_num) values (2,94);
insert into sacn_channel (id_sacn, ch_num) values (2,95);
insert into sacn_channel (id_sacn, ch_num) values (2,96);
insert into sacn_channel (id_sacn, ch_num) values (2,97);
insert into sacn_channel (id_sacn, ch_num) values (2,98);
insert into sacn_channel (id_sacn, ch_num) values (2,99);
insert into sacn_channel (id_sacn, ch_num) values (2,100);
insert into sacn_channel (id_sacn, ch_num) values (2,101);
insert into sacn_channel (id_sacn, ch_num) values (2,102);
insert into sacn_channel (id_sacn, ch_num) values (2,103);
insert into sacn_channel (id_sacn, ch_num) values (2,104);
insert into sacn_channel (id_sacn, ch_num) values (2,105);
insert into sacn_channel (id_sacn, ch_num) values (2,106);
insert into sacn_channel (id_sacn, ch_num) values (2,107);
insert into sacn_channel (id_sacn, ch_num) values (2,108);
insert into sacn_channel (id_sacn, ch_num) values (2,109);
insert into sacn_channel (id_sacn, ch_num) values (2,110);
insert into sacn_channel (id_sacn, ch_num) values (2,111);
insert into sacn_channel (id_sacn, ch_num) values (2,112);
insert into sacn_channel (id_sacn, ch_num) values (2,113);
insert into sacn_channel (id_sacn, ch_num) values (2,114);
insert into sacn_channel (id_sacn, ch_num) values (2,115);
insert into sacn_channel (id_sacn, ch_num) values (2,116);
insert into sacn_channel (id_sacn, ch_num) values (2,117);
insert into sacn_channel (id_sacn, ch_num) values (2,118);
insert into sacn_channel (id_sacn, ch_num) values (2,119);
insert into sacn_channel (id_sacn, ch_num) values (2,120);
insert into sacn_channel (id_sacn, ch_num) values (2,121);
insert into sacn_channel (id_sacn, ch_num) values (2,122);
insert into sacn_channel (id_sacn, ch_num) values (2,123);
insert into sacn_channel (id_sacn, ch_num) values (2,124);
insert into sacn_channel (id_sacn, ch_num) values (2,125);
insert into sacn_channel (id_sacn, ch_num) values (2,126);
insert into sacn_channel (id_sacn, ch_num) values (2,127);
insert into sacn_channel (id_sacn, ch_num) values (2,128);
insert into sacn_channel (id_sacn, ch_num) values (2,129);
insert into sacn_channel (id_sacn, ch_num) values (2,130);
insert into sacn_channel (id_sacn, ch_num) values (2,131);
insert into sacn_channel (id_sacn, ch_num) values (2,132);
insert into sacn_channel (id_sacn, ch_num) values (2,133);
insert into sacn_channel (id_sacn, ch_num) values (2,134);
insert into sacn_channel (id_sacn, ch_num) values (2,135);
insert into sacn_channel (id_sacn, ch_num) values (2,136);
insert into sacn_channel (id_sacn, ch_num) values (2,137);
insert into sacn_channel (id_sacn, ch_num) values (2,138);
insert into sacn_channel (id_sacn, ch_num) values (2,139);
insert into sacn_channel (id_sacn, ch_num) values (2,140);
insert into sacn_channel (id_sacn, ch_num) values (2,141);
insert into sacn_channel (id_sacn, ch_num) values (2,142);
insert into sacn_channel (id_sacn, ch_num) values (2,143);
insert into sacn_channel (id_sacn, ch_num) values (2,144);
insert into sacn_channel (id_sacn, ch_num) values (2,145);
insert into sacn_channel (id_sacn, ch_num) values (2,146);
insert into sacn_channel (id_sacn, ch_num) values (2,147);
insert into sacn_channel (id_sacn, ch_num) values (2,148);
insert into sacn_channel (id_sacn, ch_num) values (2,149);
insert into sacn_channel (id_sacn, ch_num) values (2,150);
insert into sacn_channel (id_sacn, ch_num) values (2,151);
insert into sacn_channel (id_sacn, ch_num) values (2,152);
insert into sacn_channel (id_sacn, ch_num) values (2,153);
insert into sacn_channel (id_sacn, ch_num) values (2,154);
insert into sacn_channel (id_sacn, ch_num) values (2,155);
insert into sacn_channel (id_sacn, ch_num) values (2,156);
insert into sacn_channel (id_sacn, ch_num) values (2,157);
insert into sacn_channel (id_sacn, ch_num) values (2,158);
insert into sacn_channel (id_sacn, ch_num) values (2,159);
insert into sacn_channel (id_sacn, ch_num) values (2,160);
insert into sacn_channel (id_sacn, ch_num) values (2,161);
insert into sacn_channel (id_sacn, ch_num) values (2,162);
insert into sacn_channel (id_sacn, ch_num) values (2,163);
insert into sacn_channel (id_sacn, ch_num) values (2,164);
insert into sacn_channel (id_sacn, ch_num) values (2,165);
insert into sacn_channel (id_sacn, ch_num) values (2,166);
insert into sacn_channel (id_sacn, ch_num) values (2,167);
insert into sacn_channel (id_sacn, ch_num) values (2,168);
insert into sacn_channel (id_sacn, ch_num) values (2,169);
insert into sacn_channel (id_sacn, ch_num) values (2,170);
insert into sacn_channel (id_sacn, ch_num) values (2,171);
insert into sacn_channel (id_sacn, ch_num) values (2,172);
insert into sacn_channel (id_sacn, ch_num) values (2,173);
insert into sacn_channel (id_sacn, ch_num) values (2,174);
insert into sacn_channel (id_sacn, ch_num) values (2,175);
insert into sacn_channel (id_sacn, ch_num) values (2,176);
insert into sacn_channel (id_sacn, ch_num) values (2,177);
insert into sacn_channel (id_sacn, ch_num) values (2,178);
insert into sacn_channel (id_sacn, ch_num) values (2,179);
insert into sacn_channel (id_sacn, ch_num) values (2,180);
insert into sacn_channel (id_sacn, ch_num) values (2,181);
insert into sacn_channel (id_sacn, ch_num) values (2,182);
insert into sacn_channel (id_sacn, ch_num) values (2,183);
insert into sacn_channel (id_sacn, ch_num) values (2,184);
insert into sacn_channel (id_sacn, ch_num) values (2,185);
insert into sacn_channel (id_sacn, ch_num) values (2,186);
insert into sacn_channel (id_sacn, ch_num) values (2,187);
insert into sacn_channel (id_sacn, ch_num) values (2,188);
insert into sacn_channel (id_sacn, ch_num) values (2,189);
insert into sacn_channel (id_sacn, ch_num) values (2,190);
insert into sacn_channel (id_sacn, ch_num) values (2,191);
insert into sacn_channel (id_sacn, ch_num) values (2,192);
insert into sacn_channel (id_sacn, ch_num) values (2,193);
insert into sacn_channel (id_sacn, ch_num) values (2,194);
insert into sacn_channel (id_sacn, ch_num) values (2,195);
insert into sacn_channel (id_sacn, ch_num) values (2,196);
insert into sacn_channel (id_sacn, ch_num) values (2,197);
insert into sacn_channel (id_sacn, ch_num) values (2,198);
insert into sacn_channel (id_sacn, ch_num) values (2,199);
insert into sacn_channel (id_sacn, ch_num) values (2,200);
insert into sacn_channel (id_sacn, ch_num) values (2,201);
insert into sacn_channel (id_sacn, ch_num) values (2,202);
insert into sacn_channel (id_sacn, ch_num) values (2,203);
insert into sacn_channel (id_sacn, ch_num) values (2,204);
insert into sacn_channel (id_sacn, ch_num) values (2,205);
insert into sacn_channel (id_sacn, ch_num) values (2,206);
insert into sacn_channel (id_sacn, ch_num) values (2,207);
insert into sacn_channel (id_sacn, ch_num) values (2,208);
insert into sacn_channel (id_sacn, ch_num) values (2,209);
insert into sacn_channel (id_sacn, ch_num) values (2,210);
insert into sacn_channel (id_sacn, ch_num) values (2,211);
insert into sacn_channel (id_sacn, ch_num) values (2,212);
insert into sacn_channel (id_sacn, ch_num) values (2,213);
insert into sacn_channel (id_sacn, ch_num) values (2,214);
insert into sacn_channel (id_sacn, ch_num) values (2,215);
insert into sacn_channel (id_sacn, ch_num) values (2,216);
insert into sacn_channel (id_sacn, ch_num) values (2,217);
insert into sacn_channel (id_sacn, ch_num) values (2,218);
insert into sacn_channel (id_sacn, ch_num) values (2,219);
insert into sacn_channel (id_sacn, ch_num) values (2,220);
insert into sacn_channel (id_sacn, ch_num) values (2,221);
insert into sacn_channel (id_sacn, ch_num) values (2,222);
insert into sacn_channel (id_sacn, ch_num) values (2,223);
insert into sacn_channel (id_sacn, ch_num) values (2,224);
insert into sacn_channel (id_sacn, ch_num) values (2,225);
insert into sacn_channel (id_sacn, ch_num) values (2,226);
insert into sacn_channel (id_sacn, ch_num) values (2,227);
insert into sacn_channel (id_sacn, ch_num) values (2,228);
insert into sacn_channel (id_sacn, ch_num) values (2,229);
insert into sacn_channel (id_sacn, ch_num) values (2,230);
insert into sacn_channel (id_sacn, ch_num) values (2,231);
insert into sacn_channel (id_sacn, ch_num) values (2,232);
insert into sacn_channel (id_sacn, ch_num) values (2,233);
insert into sacn_channel (id_sacn, ch_num) values (2,234);
insert into sacn_channel (id_sacn, ch_num) values (2,235);
insert into sacn_channel (id_sacn, ch_num) values (2,236);
insert into sacn_channel (id_sacn, ch_num) values (2,237);
insert into sacn_channel (id_sacn, ch_num) values (2,238);
insert into sacn_channel (id_sacn, ch_num) values (2,239);
insert into sacn_channel (id_sacn, ch_num) values (2,240);
insert into sacn_channel (id_sacn, ch_num) values (2,241);
insert into sacn_channel (id_sacn, ch_num) values (2,242);
insert into sacn_channel (id_sacn, ch_num) values (2,243);
insert into sacn_channel (id_sacn, ch_num) values (2,244);
insert into sacn_channel (id_sacn, ch_num) values (2,245);
insert into sacn_channel (id_sacn, ch_num) values (2,246);
insert into sacn_channel (id_sacn, ch_num) values (2,247);
insert into sacn_channel (id_sacn, ch_num) values (2,248);
insert into sacn_channel (id_sacn, ch_num) values (2,249);
insert into sacn_channel (id_sacn, ch_num) values (2,250);
insert into sacn_channel (id_sacn, ch_num) values (2,251);
insert into sacn_channel (id_sacn, ch_num) values (2,252);
insert into sacn_channel (id_sacn, ch_num) values (2,253);
insert into sacn_channel (id_sacn, ch_num) values (2,254);
insert into sacn_channel (id_sacn, ch_num) values (2,255);
insert into sacn_channel (id_sacn, ch_num) values (2,256);
insert into sacn_channel (id_sacn, ch_num) values (2,257);
insert into sacn_channel (id_sacn, ch_num) values (2,258);
insert into sacn_channel (id_sacn, ch_num) values (2,259);
insert into sacn_channel (id_sacn, ch_num) values (2,260);
insert into sacn_channel (id_sacn, ch_num) values (2,261);
insert into sacn_channel (id_sacn, ch_num) values (2,262);
insert into sacn_channel (id_sacn, ch_num) values (2,263);
insert into sacn_channel (id_sacn, ch_num) values (2,264);
insert into sacn_channel (id_sacn, ch_num) values (2,265);
insert into sacn_channel (id_sacn, ch_num) values (2,266);
insert into sacn_channel (id_sacn, ch_num) values (2,267);
insert into sacn_channel (id_sacn, ch_num) values (2,268);
insert into sacn_channel (id_sacn, ch_num) values (2,269);
insert into sacn_channel (id_sacn, ch_num) values (2,270);
insert into sacn_channel (id_sacn, ch_num) values (2,271);
insert into sacn_channel (id_sacn, ch_num) values (2,272);
insert into sacn_channel (id_sacn, ch_num) values (2,273);
insert into sacn_channel (id_sacn, ch_num) values (2,274);
insert into sacn_channel (id_sacn, ch_num) values (2,275);
insert into sacn_channel (id_sacn, ch_num) values (2,276);
insert into sacn_channel (id_sacn, ch_num) values (2,277);
insert into sacn_channel (id_sacn, ch_num) values (2,278);
insert into sacn_channel (id_sacn, ch_num) values (2,279);
insert into sacn_channel (id_sacn, ch_num) values (2,280);
insert into sacn_channel (id_sacn, ch_num) values (2,281);
insert into sacn_channel (id_sacn, ch_num) values (2,282);
insert into sacn_channel (id_sacn, ch_num) values (2,283);
insert into sacn_channel (id_sacn, ch_num) values (2,284);
insert into sacn_channel (id_sacn, ch_num) values (2,285);
insert into sacn_channel (id_sacn, ch_num) values (2,286);
insert into sacn_channel (id_sacn, ch_num) values (2,287);
insert into sacn_channel (id_sacn, ch_num) values (2,288);
insert into sacn_channel (id_sacn, ch_num) values (2,289);
insert into sacn_channel (id_sacn, ch_num) values (2,290);
insert into sacn_channel (id_sacn, ch_num) values (2,291);
insert into sacn_channel (id_sacn, ch_num) values (2,292);
insert into sacn_channel (id_sacn, ch_num) values (2,293);
insert into sacn_channel (id_sacn, ch_num) values (2,294);
insert into sacn_channel (id_sacn, ch_num) values (2,295);
insert into sacn_channel (id_sacn, ch_num) values (2,296);
insert into sacn_channel (id_sacn, ch_num) values (2,297);
insert into sacn_channel (id_sacn, ch_num) values (2,298);
insert into sacn_channel (id_sacn, ch_num) values (2,299);
insert into sacn_channel (id_sacn, ch_num) values (2,300);
insert into sacn_channel (id_sacn, ch_num) values (2,301);
insert into sacn_channel (id_sacn, ch_num) values (2,302);
insert into sacn_channel (id_sacn, ch_num) values (2,303);
insert into sacn_channel (id_sacn, ch_num) values (2,304);
insert into sacn_channel (id_sacn, ch_num) values (2,305);
insert into sacn_channel (id_sacn, ch_num) values (2,306);
insert into sacn_channel (id_sacn, ch_num) values (2,307);
insert into sacn_channel (id_sacn, ch_num) values (2,308);
insert into sacn_channel (id_sacn, ch_num) values (2,309);
insert into sacn_channel (id_sacn, ch_num) values (2,310);
insert into sacn_channel (id_sacn, ch_num) values (2,311);
insert into sacn_channel (id_sacn, ch_num) values (2,312);
insert into sacn_channel (id_sacn, ch_num) values (2,313);
insert into sacn_channel (id_sacn, ch_num) values (2,314);
insert into sacn_channel (id_sacn, ch_num) values (2,315);
insert into sacn_channel (id_sacn, ch_num) values (2,316);
insert into sacn_channel (id_sacn, ch_num) values (2,317);
insert into sacn_channel (id_sacn, ch_num) values (2,318);
insert into sacn_channel (id_sacn, ch_num) values (2,319);
insert into sacn_channel (id_sacn, ch_num) values (2,320);
insert into sacn_channel (id_sacn, ch_num) values (2,321);
insert into sacn_channel (id_sacn, ch_num) values (2,322);
insert into sacn_channel (id_sacn, ch_num) values (2,323);
insert into sacn_channel (id_sacn, ch_num) values (2,324);
insert into sacn_channel (id_sacn, ch_num) values (2,325);
insert into sacn_channel (id_sacn, ch_num) values (2,326);
insert into sacn_channel (id_sacn, ch_num) values (2,327);
insert into sacn_channel (id_sacn, ch_num) values (2,328);
insert into sacn_channel (id_sacn, ch_num) values (2,329);
insert into sacn_channel (id_sacn, ch_num) values (2,330);
insert into sacn_channel (id_sacn, ch_num) values (2,331);
insert into sacn_channel (id_sacn, ch_num) values (2,332);
insert into sacn_channel (id_sacn, ch_num) values (2,333);
insert into sacn_channel (id_sacn, ch_num) values (2,334);
insert into sacn_channel (id_sacn, ch_num) values (2,335);
insert into sacn_channel (id_sacn, ch_num) values (2,336);
insert into sacn_channel (id_sacn, ch_num) values (2,337);
insert into sacn_channel (id_sacn, ch_num) values (2,338);
insert into sacn_channel (id_sacn, ch_num) values (2,339);
insert into sacn_channel (id_sacn, ch_num) values (2,340);
insert into sacn_channel (id_sacn, ch_num) values (2,341);
insert into sacn_channel (id_sacn, ch_num) values (2,342);
insert into sacn_channel (id_sacn, ch_num) values (2,343);
insert into sacn_channel (id_sacn, ch_num) values (2,344);
insert into sacn_channel (id_sacn, ch_num) values (2,345);
insert into sacn_channel (id_sacn, ch_num) values (2,346);
insert into sacn_channel (id_sacn, ch_num) values (2,347);
insert into sacn_channel (id_sacn, ch_num) values (2,348);
insert into sacn_channel (id_sacn, ch_num) values (2,349);
insert into sacn_channel (id_sacn, ch_num) values (2,350);
insert into sacn_channel (id_sacn, ch_num) values (2,351);
insert into sacn_channel (id_sacn, ch_num) values (2,352);
insert into sacn_channel (id_sacn, ch_num) values (2,353);
insert into sacn_channel (id_sacn, ch_num) values (2,354);
insert into sacn_channel (id_sacn, ch_num) values (2,355);
insert into sacn_channel (id_sacn, ch_num) values (2,356);
insert into sacn_channel (id_sacn, ch_num) values (2,357);
insert into sacn_channel (id_sacn, ch_num) values (2,358);
insert into sacn_channel (id_sacn, ch_num) values (2,359);
insert into sacn_channel (id_sacn, ch_num) values (2,360);
insert into sacn_channel (id_sacn, ch_num) values (2,361);
insert into sacn_channel (id_sacn, ch_num) values (2,362);
insert into sacn_channel (id_sacn, ch_num) values (2,363);
insert into sacn_channel (id_sacn, ch_num) values (2,364);
insert into sacn_channel (id_sacn, ch_num) values (2,365);
insert into sacn_channel (id_sacn, ch_num) values (2,366);
insert into sacn_channel (id_sacn, ch_num) values (2,367);
insert into sacn_channel (id_sacn, ch_num) values (2,368);
insert into sacn_channel (id_sacn, ch_num) values (2,369);
insert into sacn_channel (id_sacn, ch_num) values (2,370);
insert into sacn_channel (id_sacn, ch_num) values (2,371);
insert into sacn_channel (id_sacn, ch_num) values (2,372);
insert into sacn_channel (id_sacn, ch_num) values (2,373);
insert into sacn_channel (id_sacn, ch_num) values (2,374);
insert into sacn_channel (id_sacn, ch_num) values (2,375);
insert into sacn_channel (id_sacn, ch_num) values (2,376);
insert into sacn_channel (id_sacn, ch_num) values (2,377);
insert into sacn_channel (id_sacn, ch_num) values (2,378);
insert into sacn_channel (id_sacn, ch_num) values (2,379);
insert into sacn_channel (id_sacn, ch_num) values (2,380);
insert into sacn_channel (id_sacn, ch_num) values (2,381);
insert into sacn_channel (id_sacn, ch_num) values (2,382);
insert into sacn_channel (id_sacn, ch_num) values (2,383);
insert into sacn_channel (id_sacn, ch_num) values (2,384);
insert into sacn_channel (id_sacn, ch_num) values (2,385);
insert into sacn_channel (id_sacn, ch_num) values (2,386);
insert into sacn_channel (id_sacn, ch_num) values (2,387);
insert into sacn_channel (id_sacn, ch_num) values (2,388);
insert into sacn_channel (id_sacn, ch_num) values (2,389);
insert into sacn_channel (id_sacn, ch_num) values (2,390);
insert into sacn_channel (id_sacn, ch_num) values (2,391);
insert into sacn_channel (id_sacn, ch_num) values (2,392);
insert into sacn_channel (id_sacn, ch_num) values (2,393);
insert into sacn_channel (id_sacn, ch_num) values (2,394);
insert into sacn_channel (id_sacn, ch_num) values (2,395);
insert into sacn_channel (id_sacn, ch_num) values (2,396);
insert into sacn_channel (id_sacn, ch_num) values (2,397);
insert into sacn_channel (id_sacn, ch_num) values (2,398);
insert into sacn_channel (id_sacn, ch_num) values (2,399);
insert into sacn_channel (id_sacn, ch_num) values (2,400);
insert into sacn_channel (id_sacn, ch_num) values (2,401);
insert into sacn_channel (id_sacn, ch_num) values (2,402);
insert into sacn_channel (id_sacn, ch_num) values (2,403);
insert into sacn_channel (id_sacn, ch_num) values (2,404);
insert into sacn_channel (id_sacn, ch_num) values (2,405);
insert into sacn_channel (id_sacn, ch_num) values (2,406);
insert into sacn_channel (id_sacn, ch_num) values (2,407);
insert into sacn_channel (id_sacn, ch_num) values (2,408);
insert into sacn_channel (id_sacn, ch_num) values (2,409);
insert into sacn_channel (id_sacn, ch_num) values (2,410);
insert into sacn_channel (id_sacn, ch_num) values (2,411);
insert into sacn_channel (id_sacn, ch_num) values (2,412);
insert into sacn_channel (id_sacn, ch_num) values (2,413);
insert into sacn_channel (id_sacn, ch_num) values (2,414);
insert into sacn_channel (id_sacn, ch_num) values (2,415);
insert into sacn_channel (id_sacn, ch_num) values (2,416);
insert into sacn_channel (id_sacn, ch_num) values (2,417);
insert into sacn_channel (id_sacn, ch_num) values (2,418);
insert into sacn_channel (id_sacn, ch_num) values (2,419);
insert into sacn_channel (id_sacn, ch_num) values (2,420);
insert into sacn_channel (id_sacn, ch_num) values (2,421);
insert into sacn_channel (id_sacn, ch_num) values (2,422);
insert into sacn_channel (id_sacn, ch_num) values (2,423);
insert into sacn_channel (id_sacn, ch_num) values (2,424);
insert into sacn_channel (id_sacn, ch_num) values (2,425);
insert into sacn_channel (id_sacn, ch_num) values (2,426);
insert into sacn_channel (id_sacn, ch_num) values (2,427);
insert into sacn_channel (id_sacn, ch_num) values (2,428);
insert into sacn_channel (id_sacn, ch_num) values (2,429);
insert into sacn_channel (id_sacn, ch_num) values (2,430);
insert into sacn_channel (id_sacn, ch_num) values (2,431);
insert into sacn_channel (id_sacn, ch_num) values (2,432);
insert into sacn_channel (id_sacn, ch_num) values (2,433);
insert into sacn_channel (id_sacn, ch_num) values (2,434);
insert into sacn_channel (id_sacn, ch_num) values (2,435);
insert into sacn_channel (id_sacn, ch_num) values (2,436);
insert into sacn_channel (id_sacn, ch_num) values (2,437);
insert into sacn_channel (id_sacn, ch_num) values (2,438);
insert into sacn_channel (id_sacn, ch_num) values (2,439);
insert into sacn_channel (id_sacn, ch_num) values (2,440);
insert into sacn_channel (id_sacn, ch_num) values (2,441);
insert into sacn_channel (id_sacn, ch_num) values (2,442);
insert into sacn_channel (id_sacn, ch_num) values (2,443);
insert into sacn_channel (id_sacn, ch_num) values (2,444);
insert into sacn_channel (id_sacn, ch_num) values (2,445);
insert into sacn_channel (id_sacn, ch_num) values (2,446);
insert into sacn_channel (id_sacn, ch_num) values (2,447);
insert into sacn_channel (id_sacn, ch_num) values (2,448);
insert into sacn_channel (id_sacn, ch_num) values (2,449);
insert into sacn_channel (id_sacn, ch_num) values (2,450);
insert into sacn_channel (id_sacn, ch_num) values (2,451);
insert into sacn_channel (id_sacn, ch_num) values (2,452);
insert into sacn_channel (id_sacn, ch_num) values (2,453);
insert into sacn_channel (id_sacn, ch_num) values (2,454);
insert into sacn_channel (id_sacn, ch_num) values (2,455);
insert into sacn_channel (id_sacn, ch_num) values (2,456);
insert into sacn_channel (id_sacn, ch_num) values (2,457);
insert into sacn_channel (id_sacn, ch_num) values (2,458);
insert into sacn_channel (id_sacn, ch_num) values (2,459);
insert into sacn_channel (id_sacn, ch_num) values (2,460);
insert into sacn_channel (id_sacn, ch_num) values (2,461);
insert into sacn_channel (id_sacn, ch_num) values (2,462);
insert into sacn_channel (id_sacn, ch_num) values (2,463);
insert into sacn_channel (id_sacn, ch_num) values (2,464);
insert into sacn_channel (id_sacn, ch_num) values (2,465);
insert into sacn_channel (id_sacn, ch_num) values (2,466);
insert into sacn_channel (id_sacn, ch_num) values (2,467);
insert into sacn_channel (id_sacn, ch_num) values (2,468);
insert into sacn_channel (id_sacn, ch_num) values (2,469);
insert into sacn_channel (id_sacn, ch_num) values (2,470);
insert into sacn_channel (id_sacn, ch_num) values (2,471);
insert into sacn_channel (id_sacn, ch_num) values (2,472);
insert into sacn_channel (id_sacn, ch_num) values (2,473);
insert into sacn_channel (id_sacn, ch_num) values (2,474);
insert into sacn_channel (id_sacn, ch_num) values (2,475);
insert into sacn_channel (id_sacn, ch_num) values (2,476);
insert into sacn_channel (id_sacn, ch_num) values (2,477);
insert into sacn_channel (id_sacn, ch_num) values (2,478);
insert into sacn_channel (id_sacn, ch_num) values (2,479);
insert into sacn_channel (id_sacn, ch_num) values (2,480);
insert into sacn_channel (id_sacn, ch_num) values (2,481);
insert into sacn_channel (id_sacn, ch_num) values (2,482);
insert into sacn_channel (id_sacn, ch_num) values (2,483);
insert into sacn_channel (id_sacn, ch_num) values (2,484);
insert into sacn_channel (id_sacn, ch_num) values (2,485);
insert into sacn_channel (id_sacn, ch_num) values (2,486);
insert into sacn_channel (id_sacn, ch_num) values (2,487);
insert into sacn_channel (id_sacn, ch_num) values (2,488);
insert into sacn_channel (id_sacn, ch_num) values (2,489);
insert into sacn_channel (id_sacn, ch_num) values (2,490);
insert into sacn_channel (id_sacn, ch_num) values (2,491);
insert into sacn_channel (id_sacn, ch_num) values (2,492);
insert into sacn_channel (id_sacn, ch_num) values (2,493);
insert into sacn_channel (id_sacn, ch_num) values (2,494);
insert into sacn_channel (id_sacn, ch_num) values (2,495);
insert into sacn_channel (id_sacn, ch_num) values (2,496);
insert into sacn_channel (id_sacn, ch_num) values (2,497);
insert into sacn_channel (id_sacn, ch_num) values (2,498);
insert into sacn_channel (id_sacn, ch_num) values (2,499);
insert into sacn_channel (id_sacn, ch_num) values (2,500);
insert into sacn_channel (id_sacn, ch_num) values (2,501);
insert into sacn_channel (id_sacn, ch_num) values (2,502);
insert into sacn_channel (id_sacn, ch_num) values (2,503);
insert into sacn_channel (id_sacn, ch_num) values (2,504);
insert into sacn_channel (id_sacn, ch_num) values (2,505);
insert into sacn_channel (id_sacn, ch_num) values (2,506);
insert into sacn_channel (id_sacn, ch_num) values (2,507);
insert into sacn_channel (id_sacn, ch_num) values (2,508);
insert into sacn_channel (id_sacn, ch_num) values (2,509);
insert into sacn_channel (id_sacn, ch_num) values (2,510);
insert into sacn_channel (id_sacn, ch_num) values (2,511);
insert into sacn_channel (id_sacn, ch_num) values (2,512);

