insert into midi_device values (1, 'Launch Control', 'in');
insert into midi_device values (2, 'APC mini', 'in');
insert into midi_device values (3, 'Launch Pad MKII', 'in');
insert into midi_control values (1, 'knob',1,0,'cc',21);
insert into midi_control values (1, 'knob',2,0,'cc',22);
insert into midi_control values (1, 'knob',3,0,'cc',23);
insert into midi_control values (1, 'knob',4,0,'cc',24);
insert into midi_control values (1, 'knob',5,0,'cc',25);
insert into midi_control values (1, 'knob',6,0,'cc',26);
insert into midi_control values (1, 'knob',7,0,'cc',27);
insert into midi_control values (1, 'knob',8,0,'cc',28);
insert into midi_control values (1, 'knob',9,0,'cc',41);
insert into midi_control values (1, 'knob',10,0,'cc',42);
insert into midi_control values (1, 'knob',11,0,'cc',43);
insert into midi_control values (1, 'knob',12,0,'cc',44);
insert into midi_control values (1, 'knob',13,0,'cc',45);
insert into midi_control values (1, 'knob',14,0,'cc',46);
insert into midi_control values (1, 'knob',15,0,'cc',47);
insert into midi_control values (1, 'knob',16,0,'cc',48);
insert into midi_control values (1, 'button',1,0,'note',9);
insert into midi_control values (1, 'button',2,0,'note',10);
insert into midi_control values (1, 'button',3,0,'note',11);
insert into midi_control values (1, 'button',4,0,'note',12);
insert into midi_control values (1, 'button',5,0,'note',25);
insert into midi_control values (1, 'button',6,0,'note',26);
insert into midi_control values (1, 'button',7,0,'note',27);
insert into midi_control values (1, 'button',8,0,'note',28);
insert into midi_control values (1, 'button',9,0,'cc',114);
insert into midi_control values (1, 'button',10,0,'cc',115);
insert into midi_control values (1, 'button',11,0,'cc',116);
insert into midi_control values (1, 'button',12,0,'cc',117);
insert into sacn values (1, '2.1.1.2', 221,'out');
